### ISSUE TITLE
[Q] purpose of ibsg? what are 'boundaries'? no link to census? map view? project assistance?

### ISSUE THREAD

**Issue by rdmolony** [energy-modelling-ireland/ibsg#15]
From Philippe Lemarchand email correspondance:

- [x] [A] What do you call boundaries? Are they the geographical boundaries we select as "countyname"?

- [x] [B] I can now open the file and noted there is no difference to the SEAI file. I guess the benefit is that SEAI files are limited on the number of dwellings that can be downloaded in a single file. Your system collates them automatically rather than me doing it manually - is this correct?

- [x] [C] I had ticked the link to the 2016 census but I see no link in the csv file. Please could you tell me what information from the 2016 census we are supposed to see?

- [x] [D] Another thing you might help me understanding as Jason mentioned the use of tableau to have a map view. The BER data do not contain any street name so how is it possible to generate a more detail view of a specific area as it is done here: https://renewables.maps.arcgis.com/apps/webappviewer/index.html?id=360f7b3f6f484d7d89b967b41231daef

- [x] [E] I have never touched Tableau and I wonder, since you work in Codema, if you might be able to help us with our SEAI Stoneybatter Sustainable Energy Community project that is mentored by Codema. I have in mind to develop superposed layers of information regarding Stoneybatter area - is that possible? Is it something you would be interested in developing together?

**Comment by rdmolony** [comment]
Thanks for getting in touch Philippe!

- [A] The `Fetch Postcode BERs` button is at postcode-level (i.e. countyname) so these are the boundaries, selecting only Dublin 1 will pull out all buildings in this postcode

- [B] `ibsg` filters the raw data provided by the SEAI to remove erroneous data.  It does this by filtering the BER dataset through upper | lower bounds on a number of columns such as floor area, boiler efficiency etc.

- [C] `ibsg` does not yet (09/07/2021) link to the Census for the Postcode BERs - it does however for the closed-access Small Area BERs.  By link I mean it looks up small area | period built in the census and fills the census with corresponding BER properties.

- [D] We could extend `ibsg` to map the data but mapping is limited to Postcode level for the Postcode BERs so it mightn't be too useful for your Stoneybatter project.  I'll raise this as a feature request for someone to complete if they have the time or if seen as a priority.

- [E] We're currently developing an interactive energy model that will let you select the Stoneybatter area and play around with the building stock in that area.  I'll link it to this thread when we have a working prototype deployed!

**Comment by PhLemarchand** [comment]
Thanks Rowan for the answers.
 [E] Could you tell me more about the interactive energy model that you are developing (even before having a working prototype)? What features will it have?

**Comment by rdmolony** [comment]
No problem at all.  The README at [this repository](https://github.com/codema-dev/dublin-energy-app/tree/master) provides an overview of the functionality so far and will update as more features are added (depending on funding, deadlines and priorities for the Dublin Region Energy Masterplan project which is due to end September-ish).  Bear in mind that the linked webapp there is not currently stable!
