### ISSUE TITLE
Whoops - something went wrong with the link to the updated postcode BER filter

### ISSUE THREAD

**Issue by Tomas-Mac-Uidhir** [energy-modelling-ireland/ibsg#8]
I tried to access the updated postcode BER filter list prototype: https://share.streamlit.io/rdmolony/ibsg/main/app.py

![image](https://user-images.githubusercontent.com/64018573/124900991-84922680-dfd9-11eb-9f47-148ba070be9d.png)

Any ideas?

**Comment by rdmolony** [comment]
Was missing a dependency in the `requirements.txt`!
