### ISSUE TITLE
Log % buildings removed by each BER filter

### ISSUE THREAD

**Issue by rdmolony** [energy-modelling-ireland/ibsg#9]

**Comment by Tomas-Mac-Uidhir** [comment]
Hi Rowan,

Would it be possible to include the % impact of each filter as they are applied? I am imagining some additional column which logs the filter impact as they are applied ...

![image](https://user-images.githubusercontent.com/64018573/124909796-c8d5f480-dfe2-11eb-8369-bac82f0da816.png)

Thanks a mill
